import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  Sports: [
    {
      id: 1,
      title: "SNIPPER BOXING PROMOTION",
      date: "Sat. 2 Aug",
      description: "SANNA SURI PRESENTS SNIPPER BOXING...",
      location: "Antheri Sports Complex",
      category: "boxing",
      isOnline: false,
      prizePool: null,
      image: "/assets/Sports/img1.avif",
    },
    {
      id: 2,
      title: "CHESS TOURNAMENT",
      date: "Sun, 27 Jul onwards",
      description: "Chess Championship (Online) For All Age",
      location: "Your Place and Your Time: India",
      category: "chess",
      isOnline: true,
      prizePool: "RS.20,000",
      image: "/assets/Sports/img3.avif",
    },
    {
      id: 3,
      title: "Aamchi Mumbai Marathon",
      date: null,
      description: "Bandra Fort Garden: Mumbai",
      location: "Bandra Fort Garden: Mumbai",
      category: "marathon",
      isOnline: false,
      prizePool: null,
      image: "/assets/Sports/img4.avif",
    },
    {
      id: 4,
      title: "Together We Run Virtual Event",
      date: null,
      description: "Multiple Cities",
      location: "Multiple Cities",
      category: "marathon",
      isOnline: true,
      prizePool: null,
      image: "/assets/Sports/img5.avif",
    },
    {
      id: 5,
      title: "INFINITY CHESS CHAMPIONSHIP ONLINE",
      date: "Sun, 27 Jul",
      description: "Infinity Chess Championship",
      location: "Your Place and Your Time: India",
      category: "chess",
      isOnline: true,
      prizePool: "7.5,000+",
      prizeDetails: "FIRST PRIZE ZK",
      image: "/assets/Sports/img6.avif",
    },
    {
      id: 6,
      title: "STRIDE FOR PRIDE Marathon",
      date: "Sun, 27 Jul",
      description: "MEDAL | TROPHY",
      location: "Your Place and Your Time: India",
      category: "marathon",
      isOnline: true,
      prizePool: null,
      image: "/assets/Sports/img7.avif",
    },
    {
      id: 7,
      title: "Mahakumbh Year 2025 Marathon",
      date: "Wed, 23 Jul onwards",
      description: "2025 YOUR LOCATION YOUR TIME",
      location: "Your Place and Your Time: India",
      category: "marathon",
      isOnline: true,
      prizePool: null,
      image: "/assets/Sports/img8.avif",
    },
    {
      id: 8,
      title: "Mumbai Green Marathon - Bandra West",
      date: "Sun, 21 Sep",
      description: "Bandra Fort Garden: Mumbai",
      location: "Bandra Fort Garden: Mumbai",
      category: "marathon",
      isOnline: false,
      prizePool: null,
      image: "/assets/Sports/img9.avif",
    },
    {
      id: 9,
      title: "MILES OF GLORY 2025 MARATHON RUN",
      date: "Sun, 27 Jul onwards",
      description: null,
      location: "Your Place and Your Time: India",
      category: "marathon",
      isOnline: true,
      prizePool: null,
      image: "/assets/Sports/img10.avif",
    },
  ],
};

export const SportsSlice = createSlice({
  name: "Sports",
  initialState,
  reducers: {},
});

export const SelectSports = (state) => state.Sports.Sports;
export default SportsSlice.reducer;
