import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  latestPlays: [
    {
      id: 1,
      title: "Raju Raja Ram aur Main",
      language: "Hindi",
      startDate: "Sun, 27 Jul 2025",
      time: "7:00 PM",
      duration: "2 Hours",
      ageLimit: "10yrs+",
      genres: "Comedy, Drama",
      venue: "St. Andrews Auditorium: Mumbai",
      price: "₹499 onwards",
      alert: "Bookings are filling fast for Mumbai",
      tag: "Filling Fast",
      imageUrl: "/assets/latestPlays/img2.avif",
      banner: "/assets/latestPlays/banner1.avif",
      about:
        "A rib-tickling Hindi comedy that explores mistaken identities, family chaos, and a series of unexpected events that will leave you in splits.",
      artists: [
        { name: "Sharman Joshi", image: "/assets/latestPlays/sharman.avif" },
        { name: "Dipna Patel", image: "/assets/latestPlays/Dipna.avif" },
        { name: "Vivek Desai", image: "/assets/latestPlays/Vivek.avif" },
        { name: "Rajesh Bhosle", image: "/assets/latestPlays/Rajesh.avif" },
      ],
    },
    {
      id: 2,
      title: "Asen Me Nasen Me",
      language: "Marathi",
      startDate: "Thu, 31 Jul 2025",
      time: "8:00 PM",
      duration: "2.5 Hours",
      ageLimit: "12yrs+",
      genres: "Drama",
      venue: "Rangsharda Auditorium: Mumbai",
      price: "₹399 onwards",
      alert: "Limited seats left",
      tag: "Hurry!",
      imageUrl: "/assets/latestPlays/img3.avif",
      banner: "/assets/latestPlays/banner2.avif",
      about:
        "A thought-provoking Marathi play that delves into the complexity of human emotions, relationships, and life's unexpected turns.",
      artists: [
        { name: "Sonal Patil", image: "/assets/latestPlays/artist4.avif" },
        { name: "Rohit Bhandare", image: "/assets/latestPlays/artist5.avif" },
      ],
    },
    {
      id: 3,
      title: "Varvarche Vadhu Var",
      language: "Marathi",
      startDate: "Fri, 25 Jul 2025",
      time: "6:30 PM",
      duration: "2 Hours",
      ageLimit: "8yrs+",
      genres: "Comedy, Satire",
      venue: "Yashwantrao Chavan Natyagruha: Pune",
      price: "₹350 onwards",
      alert: "Pune shows almost full",
      tag: "Book Soon",
      imageUrl: "/assets/latestPlays/img4.avif",
      banner: "/assets/latestPlays/banner3.avif",
      about:
        "A satirical take on arranged marriages in Indian society, with witty dialogues and hilarious situations that will resonate with every generation.",
      artists: [
        { name: "Sakhi Gokhale", image: "/assets/latestPlays/artist6.avif" },
        { name: "Suvrat Joshi", image: "/assets/latestPlays/artist7.avif" },
        { name: "Suraj Parasnis", image: "/assets/latestPlays/artist8.avif" },
      ],
    },
    {
      id: 4,
      title: "Thet Tumchya Gharatun",
      language: "Marathi",
      startDate: "Fri, 25 Jul 2025",
      time: "5:30 PM",
      duration: "2 Hours",
      ageLimit: "10yrs+",
      genres: "Drama",
      venue: "Balgandharva Rangmandir: Pune",
      price: "₹299 onwards",
      alert: "Only a few seats left!",
      tag: "Almost Full",
      imageUrl: "/assets/latestPlays/img5.avif",
      banner: "/assets/latestPlays/banner4.avif",
      about:
        "A dramatic tale of unexpected visitors, family secrets, and emotional confrontations. A gripping Marathi stage performance with stellar acting.",
      artists: [
        { name: "Shweta Shinde", image: "/assets/latestPlays/artist9.avif" },
        { name: "Omkar Naik", image: "/assets/latestPlays/artist10.avif" },
      ],
    },
    {
      id: 5,
      title: "Punha Sahi Re Sahi",
      language: "Marathi",
      startDate: "Fri, 25 Jul 2025",
      time: "7:30 PM",
      duration: "2.5 Hours",
      ageLimit: "10yrs+",
      genres: "Comedy",
      venue: "Prabodhankar Thackeray Auditorium: Mumbai",
      price: "₹449 onwards",
      alert: "Fast selling show",
      tag: "Filling Fast",
      imageUrl: "/assets/latestPlays/img6.avif",
      banner: "/assets/latestPlays/banner5.avif",
      about:
        "Back by popular demand! A classic Marathi farce that’s full of mistaken identities, witty comebacks, and a plot that will keep you laughing throughout.",
      artists: [
        { name: "Bharat Jadhav", image: "/assets/latestPlays/artist11.avif" },
        { name: "Vijay Patkar", image: "/assets/latestPlays/artist12.avif" },
        { name: "Hemangi Kavi", image: "/assets/latestPlays/artist13.avif" },
      ],
    },
    {
      id: 6,
      title: "Aamne Saamne - Marathi Play",
      language: "Marathi",
      startDate: "Sat, 26 Jul 2025",
      time: "6:00 PM",
      duration: "2 Hours",
      ageLimit: "15yrs+",
      genres: "Drama",
      venue: "Tilak Smarak Mandir: Pune",
      price: "₹399 onwards",
      alert: "Book early to avoid disappointment",
      tag: "Hot Pick",
      imageUrl: "/assets/latestPlays/img7.avif",
      banner: "/assets/latestPlays/banner6.avif",
      about:
        "Two contrasting characters. One intense evening. A powerful conversation that challenges ideologies, emotions, and boundaries of human thought.",
      artists: [
        {
          name: "Madhura Velankar",
          image: "/assets/latestPlays/artist14.avif",
        },
        { name: "Vikram Gokhale", image: "/assets/latestPlays/artist15.avif" },
      ],
    },
    {
      id: 7,
      title: "Jar Tar Chi Goshta",
      language: "Marathi",
      startDate: "Sun, 10 Aug 2025",
      time: "5:00 PM",
      duration: "2 Hours",
      ageLimit: "7yrs+",
      genres: "Comedy, Family",
      venue: "Vishnudas Bhave Auditorium: Navi Mumbai",
      price: "₹299 onwards",
      alert: "Family favourite show",
      tag: "Recommended",
      imageUrl: "/assets/latestPlays/img8.avif",
      banner: "/assets/latestPlays/banner7.avif",
      about:
        "A heartwarming comedy about dreams, drama, and destiny. With colorful characters and a quirky narrative, this play is perfect for a fun weekend outing.",
      artists: [
        { name: "Supriya Pathare", image: "/assets/latestPlays/artist16.avif" },
        { name: "Anand Ingale", image: "/assets/latestPlays/artist17.avif" },
        { name: "Pushkar Shrotri", image: "/assets/latestPlays/artist18.avif" },
      ],
    },
  ],
};

export const latestPlaySlice = createSlice({
  name: "latestPlays",
  initialState,
  reducers: {},
});

export const selectLatestPlays = (state) => state.latestPlays.latestPlays;
export default latestPlaySlice.reducer;
